### ISSUE TITLE
能否让压制出来的视频画面和字幕都变成 Rec701 的色彩呢？

### ISSUE THREAD

**Issue by Yave-Yu** [1265578519/ShanaEncoder#10]
指压制非 H.264 编码的视频变成 Rec709 的色彩，比如压制 Techsmith Screen Capture Codec 编码的 AVI 视频。目前的版本我没找到选项，致使压制后的画面是绿色暗的、红蓝略亮、黄偏暖、青偏蓝的 Rec601 的色彩，而小丸不会这样，MeGUI 在 ConvertToYV12 里面加上 matrix=Rec709 后也不会这样……所以希望 ShanaEncoder 可以像小丸那样。

**Comment by 1265578519** [comment]
参数是按F8在编码设置空白处按空格键加入 -color_range pc
具体可以参考ffmpeg文档，ffmpeg的文档蛮全的，很多东西还要摸索
https://bbs.itzmx.com/thread-93778-1-1.html

这也有一份群友分享的预设合集
[22年4月更 单独预设 解压后复制presets文件夹里全部文件粘贴到shana的presets文件夹_2.zip](https://github.com/1265578519/ShanaEncoder/files/12453664/22.4.presets.shana.presets._2.zip)
