### ISSUE TITLE
能否让压制出来的字幕带上 OpenType 特性呢？

### ISSUE THREAD

**Issue by Yave-Yu** [1265578519/ShanaEncoder#11]
目前的 ShanaEncoder 支持 CJK 扩展区的字相当不错，好感上升……但也发现 OpenType 特性跟着没了，比如令冒号居中的 calt 特性。

**Comment by 1265578519** [comment]
ffmpeg不具备这个功能，可能要外挂dll过滤器实现，还是换其它字体来实现类似效果吧

**Comment by Yave-Yu** [comment]
哈哈，好吧֎
