### ISSUE TITLE
希望加入对 VSFilterMod.dll 字幕渲染压制的支持

### ISSUE THREAD

**Issue by Minhai1** [1265578519/ShanaEncoder#13]
非常感谢作者，部分特效字幕需要VSFilterMod.dll字幕滤镜进行压制，希望可以加入

**Comment by 1265578519** [comment]
现在版本还不支持，只能使用ffmpeg自带的过滤器压制ass等高级字幕特效

**Comment by Yave-Yu** [comment]
支持VSFilterMod.dll后大概就支持100%同步压制字幕了，目前只能靠MeGUI压制。
