### ISSUE TITLE
哪个是~

### ISSUE THREAD

**Issue by ABC793478** [1265578519/ShanaEncoder#14]
作者您好，请问这个项目和那个通常看到的韩国官网的软件是怎样的关系~

**Comment by 1265578519** [comment]
这个仓库提供了大陆版简体中文汉化，并且标注了一些功能作用的注释，可以让新手更好的使用上软件
目前韩国官网也提供了机器翻译的中文，不过由于是机器翻译误差会比较严重，可以自由选择使用的版本

**Comment by PaTTeeL** [comment]
求跟进6.0.1.7~

**Comment by 1265578519** [comment]
@PaTTeeL 6.0.1.7 内核没改动，主要就是界面上，需要的话那就发出来吧
