### ISSUE TITLE
如何禁用XySubFilter滤镜压制

### ISSUE THREAD

**Issue by Ayamiyyy** [1265578519/ShanaEncoder#15]
之前安装过XySubFilter滤镜，但是已经完全卸载了，注册表上也删除了。但是现在渲染字幕还是会启用这个滤镜，重新安装软件也不行

**Comment by Ayamiyyy** [comment]
> ShanaEncoder没有使用这个滤镜，默认情况下用的是shanasubtitle滤镜

那shana还有没有支持的别的字幕滤镜呢？

**Comment by 1265578519** [comment]
@Ayamiyyy ShanaEncoder底层用的是ffmpeg，只要是ff的滤镜基本都是支持的，这有一份帮助手册，可以看看
https://bbs.itzmx.com/thread-93778-1-1.html

**Comment by Ayamiyyy** [comment]
> @Ayamiyyy ShanaEncoder底层用的是ffmpeg，只要是ff的滤镜基本都是支持的，这有一份帮助手册，可以看看 https://bbs.itzmx.com/thread-93778-1-1.html
感谢！
