### ISSUE TITLE
请问如何开启GOP模式？

### ISSUE THREAD

**Issue by z13660** [1265578519/ShanaEncoder#2]

**Comment by 1265578519** [comment]
这个不用管的啊，自动的

**Comment by z136560** [comment]
我发现shana输出的视频只有I帧和P帧，如果是Pr输出的话就有I、P、B帧

**Comment by z136560** [comment]
貌似和这个有关，但是参数看不懂<x264optsBox>deblock=-3,-3:cabac:bframes=3:b-adapt=1:weightb:weightp=1:ref=3:scenecut=40:ipratio=1.4:pbratio=1.3:qcomp=0.60:rc-lookahead=0:mbtree:aq-mode=2:aq-strength=1:chroma-me:merange=16:me=umh:subme=8:direct=spatial:trellis=2:psy-rd=0.50,0.2:psy:dct-decimate:no-fast-pskip:mixed-refs:ssim:sliced-threads:force-cfr</x264optsBox>

**Comment by 1265578519** [comment]
你估计得找专业的老哥问问了，我也看不懂
