### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by chenxuuu** [1265578519/ShanaEncoder#3]
二进制文件建议扔release里。。。

**Comment by 1265578519** [comment]
主要考虑到release不方便使用客户端进行同步更新上传

**Comment by chenxuuu** [comment]
上传有http接口来着。。

获取新版也有接口

https://api.github.com/repos/1265578519/ShanaEncoder/releases/latest

**Comment by 1265578519** [comment]
这个，，我知道，不就是图个GUI嘛，客户端都没release这功能
