### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by zpzhangwenhan** [1265578519/ShanaEncoder#4]
官网的ShanaEncoder有简体中文，与你这个有啥区别

**Comment by 1265578519** [comment]
官方翻译是机器翻译，很多地方不准确，也欢迎通过官方的翻译渠道修改
https://shana.pe.kr/shanaencoder_board_intl/102377
https://docs.google.com/spreadsheets/d/1RHncJnmZ8RFj5hFhivvRxz2fK4DI1pRovEHCLuuTC90/edit?usp=sharing
这里的补丁提供了更精准的ffmpeg专业翻译
