### ISSUE TITLE
压缩请教

### ISSUE THREAD

**Issue by b1fly** [1265578519/ShanaEncoder#8]
请问，H264压缩1G以下的视频，该如何设置参数呢 肉眼看不出画质损失 尽可能地压缩体积就行

**Comment by 1265578519** [comment]
[webdl 网页在线视频小文件画质.zip](https://github.com/1265578519/ShanaEncoder/files/9565187/webdl.zip)

看你的需求，应该是用于网络在线播放，你可以试一下这个预设

**Comment by b1fly** [comment]
> [webdl 网页在线视频小文件画质.zip](https://github.com/1265578519/ShanaEncoder/files/9565187/webdl.zip)
> 
> 看你的需求，应该是用于网络在线播放，你可以试一下这个预设

好的 谢谢 我试一下
